// Generated by scripts/generate-contracts.py; edit the versioned schema.
export interface ChatRequestInput {
  scope: string;
  thread_id: string;
  text: string;
  model: string;
  effort: string;
  effort_control: string;
  attachments?: Array<string>;
}
export interface ChatRequestReceipt {
  request_id: string;
  session_id: string;
  thread_id: string;
  turn_id: string;
  request: ChatRequestInput | null;
  state: "accepted" | "starting" | "running" | "completed" | "failed" | "interrupted" | "uncertain" | "reviewed" | "abandoned" | "deleted";
  error_code?: string;
  revision: number;
  created_at: string;
  updated_at: string;
}
export interface ChatRequestResponse {
  version: 1;
  receipt: ChatRequestReceipt;
  replayed?: boolean;
}
export interface ChatRequestList {
  version: 1;
  scope: string;
  requests: Array<ChatRequestReceipt>;
  pending: ChatRequestReceipt | null;
}
export interface ChatRequestEvent {
  type: "chat_request";
  version: 1;
  receipt: ChatRequestReceipt;
}
export interface APIProblem {
  error?: string;
  code?: string;
  operation_id?: string;
  hint?: string;
  action?: string;
  retryable?: boolean;
}
