# Loaded by /etc/bash.bashrc before the user's ~/.bashrc.
case $- in
  *i*) ;;
  *) return ;;
esac

case "$TERM" in
  xterm*|screen*|tmux*|*-256color)
    PS1='\[\e[32m\]\u@\h\[\e[0m\]:\[\e[34m\]\w\[\e[0m\]\$ '
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    ;;
esac
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
