#!/usr/bin/env python3
"""Generate only the M1/M3 wire types, not the entire API. No third-party runtime."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def ts_type(schema):
    if '$ref' in schema:
        return schema['$ref'].split('/')[-1]
    if 'const' in schema:
        return json.dumps(schema['const'])
    if 'enum' in schema:
        return ' | '.join(json.dumps(value) for value in schema['enum'])
    if 'anyOf' in schema:
        return ' | '.join(ts_type(value) for value in schema['anyOf'])
    kind = schema['type']
    if kind == 'array':
        return f'Array<{ts_type(schema["items"])}>'
    return {'string': 'string', 'integer': 'number', 'boolean': 'boolean', 'null': 'null'}[kind]


def generate():
    schema = json.loads((ROOT / 'contracts/chat-errors-v1.schema.json').read_text())
    lines = ['// Generated by scripts/generate-contracts.py; edit the versioned schema.']
    for name, value in schema['$defs'].items():
        lines.append(f'export interface {name} {{')
        for key, prop in value['properties'].items():
            optional = '' if key in value['required'] else '?'
            lines.append(f'  {key}{optional}: {ts_type(prop)};')
        lines.append('}')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'web/src/contracts/v1.d.ts'
    content = generate()
    if args.check:
        if not path.exists() or path.read_text() != content:
            parser.exit(1, 'Contract types are stale; run python3 scripts/generate-contracts.py\n')
    else:
        path.write_text(content)
